/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package watch;

import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author dinglasamo_sd2082
 */
public class Tanan extends javax.swing.JFrame {
  int hrs=0;
  int mins=0;
  int sec=0;
  int numcount=0;
  int numcountdown=10;
  boolean stop =false;
  boolean cdownstop=false;
  boolean currenttimestart1=true;
  
 

   
    public Tanan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtontimerstart = new javax.swing.JButton();
        jButtontimerstop = new javax.swing.JButton();
        timerhour = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        timerminutes = new javax.swing.JLabel();
        timersecond = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        currenttimestart = new javax.swing.JButton();
        currenttimelabel = new javax.swing.JLabel();
        currenttimestop = new javax.swing.JButton();
        countuppanel = new javax.swing.JPanel();
        jButtonstartup = new javax.swing.JButton();
        jButtonstopup = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        numbercountup = new javax.swing.JLabel();
        panelcountdown = new javax.swing.JPanel();
        jButtondownstart = new javax.swing.JButton();
        jButtondownstop = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        numbercountdown = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.pink, null, null));

        jButtontimerstart.setBackground(new java.awt.Color(0, 51, 204));
        jButtontimerstart.setText("start");
        jButtontimerstart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtontimerstartActionPerformed(evt);
            }
        });

        jButtontimerstop.setBackground(new java.awt.Color(0, 51, 204));
        jButtontimerstop.setText("stop");
        jButtontimerstop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtontimerstopActionPerformed(evt);
            }
        });

        timerhour.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 36)); // NOI18N
        timerhour.setText(":00");

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 36)); // NOI18N
        jLabel5.setText("Timer");

        timerminutes.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 36)); // NOI18N
        timerminutes.setText(":00");

        timersecond.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 36)); // NOI18N
        timersecond.setText(":00");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(timerhour, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timerminutes, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(timersecond, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jButtontimerstart)
                        .addGap(46, 46, 46)
                        .addComponent(jButtontimerstop)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(timerhour, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(timerminutes, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(timersecond, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtontimerstart)
                    .addComponent(jButtontimerstop))
                .addGap(48, 48, 48))
        );

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 0, 204)));

        jLabel2.setBackground(new java.awt.Color(51, 51, 255));
        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 36)); // NOI18N
        jLabel2.setText("Current Time");

        currenttimestart.setBackground(new java.awt.Color(0, 153, 153));
        currenttimestart.setText("start");
        currenttimestart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currenttimestartActionPerformed(evt);
            }
        });

        currenttimelabel.setFont(new java.awt.Font("Viner Hand ITC", 1, 24)); // NOI18N
        currenttimelabel.setText("00:00:00");

        currenttimestop.setBackground(new java.awt.Color(0, 153, 153));
        currenttimestop.setText("stop");
        currenttimestop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currenttimestopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(currenttimestart)
                        .addGap(74, 74, 74)
                        .addComponent(currenttimestop))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 55, Short.MAX_VALUE)
                .addComponent(currenttimelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(currenttimelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(currenttimestart)
                    .addComponent(currenttimestop))
                .addGap(31, 31, 31))
        );

        countuppanel.setBackground(new java.awt.Color(204, 204, 255));
        countuppanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.red, java.awt.Color.green, null, null));

        jButtonstartup.setBackground(new java.awt.Color(0, 255, 255));
        jButtonstartup.setText("start");
        jButtonstartup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonstartupActionPerformed(evt);
            }
        });

        jButtonstopup.setBackground(new java.awt.Color(0, 255, 255));
        jButtonstopup.setText("stop");
        jButtonstopup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonstopupActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 36)); // NOI18N
        jLabel4.setText("Count Up");

        numbercountup.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 36)); // NOI18N
        numbercountup.setText("0");

        javax.swing.GroupLayout countuppanelLayout = new javax.swing.GroupLayout(countuppanel);
        countuppanel.setLayout(countuppanelLayout);
        countuppanelLayout.setHorizontalGroup(
            countuppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(countuppanelLayout.createSequentialGroup()
                .addGroup(countuppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(countuppanelLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jButtonstartup)
                        .addGap(73, 73, 73)
                        .addComponent(jButtonstopup))
                    .addGroup(countuppanelLayout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jLabel4)))
                .addContainerGap(89, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, countuppanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(numbercountup, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        countuppanelLayout.setVerticalGroup(
            countuppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, countuppanelLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(numbercountup, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(countuppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonstartup)
                    .addComponent(jButtonstopup))
                .addGap(45, 45, 45))
        );

        panelcountdown.setBackground(new java.awt.Color(51, 255, 204));
        panelcountdown.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 0), 1, true));

        jButtondownstart.setBackground(new java.awt.Color(153, 0, 153));
        jButtondownstart.setText("start");
        jButtondownstart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtondownstartActionPerformed(evt);
            }
        });

        jButtondownstop.setBackground(new java.awt.Color(153, 0, 153));
        jButtondownstop.setText("stop");
        jButtondownstop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtondownstopActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 36)); // NOI18N
        jLabel6.setText("Count Down");

        numbercountdown.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 36)); // NOI18N
        numbercountdown.setText("10");

        javax.swing.GroupLayout panelcountdownLayout = new javax.swing.GroupLayout(panelcountdown);
        panelcountdown.setLayout(panelcountdownLayout);
        panelcountdownLayout.setHorizontalGroup(
            panelcountdownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelcountdownLayout.createSequentialGroup()
                .addGroup(panelcountdownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelcountdownLayout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jButtondownstart)
                        .addGap(69, 69, 69)
                        .addComponent(jButtondownstop))
                    .addGroup(panelcountdownLayout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabel6))
                    .addGroup(panelcountdownLayout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(numbercountdown, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelcountdownLayout.setVerticalGroup(
            panelcountdownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelcountdownLayout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(numbercountdown, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(panelcountdownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtondownstart)
                    .addComponent(jButtondownstop))
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(countuppanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelcountdown, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelcountdown, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(countuppanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void currenttimestartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currenttimestartActionPerformed
            currenttimestart1=true;
        Thread thr=new Thread(){
                public void run(){
                    for(;;){
                        if(currenttimestart1==true){
                            try{
                                Date d= new Date();
                                SimpleDateFormat dtf = new   SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
                                 currenttimelabel.setText(dtf.format(d));
                            }
                            catch(Exception e){
                                System.out.println(e.getMessage());
                                break;
                            }
                        }
                    }
                }
            };
        thr.start();
    }//GEN-LAST:event_currenttimestartActionPerformed

    private void jButtontimerstopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtontimerstopActionPerformed
            stop=false;
            Thread t = new Thread(){
                public void run(){
                    for(;;){
                        
                    }
                }
            };
    }//GEN-LAST:event_jButtontimerstopActionPerformed

    private void jButtontimerstartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtontimerstartActionPerformed
        stop=true;
        Thread th;
      th = new Thread(){
          public void run(){
              for (;;){
                  if(stop==true){
                      try{
                        sleep(1000);
                        if(sec==60){
                            sec=0;
                            mins++;
                        }
                        if(mins==60){
                            sec=0;
                            hrs++;
                        }
                        timersecond.setText(":"+sec);
                        timerminutes.setText(":"+mins);
                        timerhour.setText(":"+hrs);
                        sec++;
                      }
                      catch( Exception e){
                          System.out.println(e.getMessage());
                      }
                  }else{
                      break;
                  }
              }
          }
      };
      th.start();
    }//GEN-LAST:event_jButtontimerstartActionPerformed

    private void jButtondownstartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtondownstartActionPerformed
      cdownstop=true;
      Thread t;
      t = new Thread(){
          public void run(){
              for(;;){
                  if(cdownstop==true){
                      try{
                          sleep(1000);
                          if(numcountdown !=0){
                              numcountdown--;
                          }else if (numcountdown==0){
                              panelcountdown.setBackground(Color.red);
                          }
                          numbercountdown.setText(""+numcountdown);
                      }
                      catch(Exception e){
                          System.out.println(e.getMessage());
                          break;
                      }
                  }
              }
          }
      };
      t.start();
    }//GEN-LAST:event_jButtondownstartActionPerformed

    private void jButtonstartupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonstartupActionPerformed
        stop=true;
        Thread th=new Thread(){
            public void run(){
                for(;;){
                   if(stop==true) {
                       try{
                           sleep(1000);
                          numcount++;
                          if(numcount==11){
                              countuppanel.setBackground(Color.blue);
                              break;
                          }
                          numbercountup.setText(""+numcount);
                       }
                       catch(Exception e){
                           System.out.println(e.getMessage());
                           break;
                       }
                   }
                }
            }
        };
        th.start();
    }//GEN-LAST:event_jButtonstartupActionPerformed

    private void jButtonstopupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonstopupActionPerformed
      stop=false;
    }//GEN-LAST:event_jButtonstopupActionPerformed

    private void jButtondownstopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtondownstopActionPerformed
       cdownstop=false;
    }//GEN-LAST:event_jButtondownstopActionPerformed

    private void currenttimestopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currenttimestopActionPerformed
        currenttimestart1=false;
    }//GEN-LAST:event_currenttimestopActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tanan().setVisible(true);
                 Thread t = new Thread();
   
            
        t.start();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel countuppanel;
    private javax.swing.JLabel currenttimelabel;
    private javax.swing.JButton currenttimestart;
    private javax.swing.JButton currenttimestop;
    private javax.swing.JButton jButtondownstart;
    private javax.swing.JButton jButtondownstop;
    private javax.swing.JButton jButtonstartup;
    private javax.swing.JButton jButtonstopup;
    private javax.swing.JButton jButtontimerstart;
    private javax.swing.JButton jButtontimerstop;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel numbercountdown;
    private javax.swing.JLabel numbercountup;
    private javax.swing.JPanel panelcountdown;
    private javax.swing.JLabel timerhour;
    private javax.swing.JLabel timerminutes;
    private javax.swing.JLabel timersecond;
    // End of variables declaration//GEN-END:variables
}
